#!/bin/bash

clear
cyan='\e[1;36m%s\e[0m\n'
green='\e[1;32m%s\e[0m\n'
printf "$cyan"
./.banner
printf "$green" "Note Give all subdomains as a input"
echo ""
read -p "Enter the full path with file name: " fl
read -p "Enter company name: " comp
mkdir ~/recon/$comp/ &> /dev/null
cd ~/recon/$comp/
mkdir ziva &> /dev/null
cd ziva
cat $fl | httprobe -c 1000  | tee  ~/recon/$comp/ziva/hosts
meg -c 1000 /index.html
cat ~/recon/$comp/ziva/out/index | grep "200 OK" | cut -d"/" -f2 > ~/recon/$comp/ziva/live-200.txt
rm ~/recon/$comp/ziva/hosts
rm -r out
cat ~/recon/$comp/ziva/live-200.txt | gau | tee  ~/recon/$comp/ziva/hosts
meg -c 100 -X OPTIONS hack.html
cd out/
cat */* | grep -nr "Allow:" | tee ~/recon/$comp/ziva/z1v4.txt
